### ISSUE TITLE
This webpage is not available

### ISSUE THREAD

**Issue by mixolidia** [esparta/gitimmersion-spanish#2]
Hola,

Chrome dice "This webpage is not available" cuando trato de ir a http://gitimmersion.mx/.
Me gustaría poder aprender Git en Español.

Gracias.

**Comment by esparta** [comment]
Hola
Lamentablemente el dominio http://gitimmersion.mx/ fue dado de baja por falta de pago. Los amigos de nic.mx pretenden cobrar USD$45 al año por él, cosa que, siendo un proyecto sin fines de lucro (y sin auspicios) es simplemente incosteable.
Ya publicare luego alguna ruta alternativa (probablemente una pagina de github) cuando tenga tiempo de configurarla.

**Comment by DpdC** [comment]
Desde está URL se tiene acceso: 

> http://esparta.github.io/gitimmersion-spanish/
